theme: jekyll-theme-leap-day
title: WIREDS
description: International Workshop on Intertwining Research & Education on Software 
background: "/img/background.jpg"
repository: wireds2024/wireds2024.github.io
