theme: jekyll-theme-cayman
title: WIREDS
description: "The First International Workshop on Intertwining Research & Education on Software <br> 6th - 8th December 2024 Osaka, Japan"
background: "/img/background.jpg"
repository: wireds2024/wireds2024.github.io
